---
deployment:
  tasks:
    - export DEPLOYPATH=/home/acannorgeno/public_html/
    - /bin/rsync -av --delete-after assets $DEPLOYPATH
    - /bin/rsync -av --delete-after vendor $DEPLOYPATH
    - /bin/rsync -av --delete-after --exclude cache --exclude accounts --exclude config site $DEPLOYPATH
    - /bin/rsync -av .htaccess composer.* favicon.ico index.php $DEPLOYPATH
