---
deployment:
  tasks:
    - export DEPLOYPATH=/home/acannorgeno/public_html/
    - /bin/rsync -a --delete-after --exclude={'kirby', 'content', '.cpanel.yml', '.editorconfig','.gitignore', '*.bat', 'site/cache', 'site/accounts', 'site/config'} ./ $DEPLOYPATH
