---
deployment:
  tasks:
    - export DEPLOYPATH=/home/acannorgeno/public_html/
    - /bin/cp -TR assets $DEPLOYPATH
    - /bin/cp -TR vendor $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - export SITEPATH=/home/acannorgeno/public_html/site/
    - /bin/cp -TR site/blueprints $SITEPATH/blueprints
    - /bin/cp -TR site/collections $SITEPATH/collections
    - /bin/cp -TR site/controllers $SITEPATH/controllers
    - /bin/cp -TR site/models $SITEPATH/models
    - /bin/cp -TR site/plugins $SITEPATH/plugins
    - /bin/cp -TR site/snippets $SITEPATH/snippets
    - /bin/cp -TR site/templates $SITEPATH/templates
