---
deployment:
  tasks:
    - export DEPLOYPATH=/home/acannorgeno/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R kirby $DEPLOYPATH
    - /bin/cp -R site $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
