columns:
  - width: 1/2
    sections:
      pages:
        type: pages
        create: default
        templates:
          - default
          - home

  - width: 1/2
    sections:
      events: sections/events
